// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEM17Uu63LO4uCu4w5Snadu462W_qqypo',
    appId: '1:264155203137:web:793844ffc0c2a8bec1e8c0',
    messagingSenderId: '264155203137',
    projectId: 'fitstrong-gym',
    authDomain: 'fitstrong-gym.firebaseapp.com',
    storageBucket: 'fitstrong-gym.appspot.com',
    measurementId: 'G-MYT22Z659Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfEztCM2sEoCFzw0nokhCsAs8HJPeYHqg',
    appId: '1:264155203137:android:9aaa02fdf7421681c1e8c0',
    messagingSenderId: '264155203137',
    projectId: 'fitstrong-gym',
    storageBucket: 'fitstrong-gym.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx3dQCz-VUlb4_yc8N2u-muzbGHzPt58Q',
    appId: '1:264155203137:ios:9eb3183ee123d646c1e8c0',
    messagingSenderId: '264155203137',
    projectId: 'fitstrong-gym',
    storageBucket: 'fitstrong-gym.appspot.com',
    iosBundleId: 'com.example.fitstrongcheckin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx3dQCz-VUlb4_yc8N2u-muzbGHzPt58Q',
    appId: '1:264155203137:ios:9eb3183ee123d646c1e8c0',
    messagingSenderId: '264155203137',
    projectId: 'fitstrong-gym',
    storageBucket: 'fitstrong-gym.appspot.com',
    iosBundleId: 'com.example.fitstrongcheckin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEM17Uu63LO4uCu4w5Snadu462W_qqypo',
    appId: '1:264155203137:web:9cb6f6284ac7c269c1e8c0',
    messagingSenderId: '264155203137',
    projectId: 'fitstrong-gym',
    authDomain: 'fitstrong-gym.firebaseapp.com',
    storageBucket: 'fitstrong-gym.appspot.com',
    measurementId: 'G-VTJ8QGF9YG',
  );
}
